

#postgresql://srivanya:lUK3byX0vMaEadXUbt7Plqjib8rYN0un@dpg-d6qit5qa214c739g3mig-a.oregon-postgres.render.com/calendereventdb

#lUK3byX0vMaEadXUbt7Plqjib8rYN0un
#dpg-d6qit5qa214c739g3mig-a.oregon-postgres.render.com
#dpg-d6qit5qa214c739g3mig-a


server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d6qit5qa214c739g3mig-a.oregon-postgres.render.com:5432/calendereventdb
spring.datasource.username=srivanya
spring.datasource.password=lUK3byX0vMaEadXUbt7Plqjib8rYN0un
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=false